### PR TITLE
label-pull-requests: add `missing_content` regex

### PR DESCRIPTION
**Pull request by SeekingMeaning**
Not sure if this is necessary or even works

Related: Homebrew/homebrew-core#58903

### CODE REVIEW

**Comment by jonchang** [comment]
Maybe `missing_content` instead of `missing` to be clearer?

**Comment by jonchang** [comment]
I think we do want this, though, since it should be our goal to get a license into every formula and it will help to flag formulae during e.g. version bumps that they don't have a license.

**Comment by dawidd6** [comment]
I'm wondering if having a field for matching PR title would be useful to us. For example if someone names their PR like: `Update xyz to a.b.c`, then we would slap a label `wrong title` or something.

**Comment by dawidd6** [comment]
Also maybe we can do the unlabel thing too. When PR changes and a label doesn't apply anymore, then delete it?

**Comment by MikeMcQuaid** [comment]
> Also maybe we can do the unlabel thing too. When PR changes and a label doesn't apply anymore, then delete it?

Yes, this would be good.

**Comment by dawidd6** [comment]
Good job @SeekingMeaning !

**Pull request merged**
