### PR TITLE
Add brew-script Action

### PR DESCRIPTION
**Pull request by dawidd6**
A new Action that allows us to run for example `ohai "hello"` simply. It's similar to `actions/github-script` Action, but for running Ruby scripts in Homebrew environment via `brew ruby` command.

cc @jonchang

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Where/how is this currently used? If it's not yet: where would it be?

I think it would be good to keep this repo to only the stuff we're using (or going to use) in our workflow files for the time being (which may include this).

**Comment by dawidd6** [comment]
This could allow us to skip writing JavaScript and write Ruby instead. I mean, I know we should be making more full-fledged Actions instead of writing programming languages code in YAML, but... yea.

No need to merge it just yet.

**Comment by MikeMcQuaid** [comment]
Sounds cool. What's an example you can think of that might be useful?

**Comment by dawidd6** [comment]
Currently, none to be honest and don't want to force ideas.

**Comment by dawidd6** [comment]
Merging as is.

**Pull request merged**
