### PR TITLE
bump-formulae: use `brew bump`.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Requires https://github.com/Homebrew/brew/pull/12702
Fixes https://github.com/Homebrew/brew/issues/5725

Use `brew bump` directly instead of the Ruby code here.

CC @dawidd6 @samford @chenrui333 @carlocab for thoughts and feedback

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Review by carlocab — COMMENTED** [review]
The Ruby script seems to handle installing `pipgrip` before calling `bump-formula-pr`, which isn't done in Homebrew/brew#12702.

If that handling is still necessary, we probably want to do that elsewhere (in `bump-formula-pr`, maybe?) before doing this.

**Comment by MikeMcQuaid** [comment]
> The Ruby script seems to handle installing `pipgrip` before calling `bump-formula-pr`, which isn't done in [Homebrew/brew#12702](https://github.com/Homebrew/brew/pull/12702).

Agreed 👍🏻

**Comment by chenrui333** [comment]
Nice catch, I realized I never used `bump` command myself in the past 😆

**Comment by MikeMcQuaid** [comment]
@carlocab Good call, doing that in https://github.com/Homebrew/brew/pull/12703.

**Review by samford — APPROVED** [review]
Outside of the `pipgrip` issue (already addressed), there are some changes that will be needed in the `brew bump` PR to maintain this action's behavior (I added related suggestions/comments). I imagine we won't merge this PR until sometime after the `brew bump` one, so the changes here look fine to me 👍

**Comment by MikeMcQuaid** [comment]
Thanks all!

**Pull request merged**
