### PR TITLE
wait-for-idle-runner: improvements

### PR DESCRIPTION
**Pull request by iMichka**
2021-05-17T13:41:19.0375029Z internal/modules/cjs/loader.js:800
2021-05-17T13:41:19.0375807Z     throw err;
2021-05-17T13:41:19.0376412Z     ^
2021-05-17T13:41:19.0376787Z
2021-05-17T13:41:19.0378996Z Error: Cannot find module '@octokit/action'
2021-05-17T13:41:19.0379729Z Require stack:
2021-05-17T13:41:19.0380996Z - /home/runner/work/_actions/Homebrew/actions/master/wait-for-idle-runner/main.js
2021-05-17T13:41:19.0382495Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
2021-05-17T13:41:19.0383670Z     at Function.Module._load (internal/modules/cjs/loader.js:690:27)
2021-05-17T13:41:19.0384885Z     at Module.require (internal/modules/cjs/loader.js:852:19)
2021-05-17T13:41:19.0385861Z     at require (internal/modules/cjs/helpers.js:74:18)
2021-05-17T13:41:19.0387606Z     at Object.<anonymous> (/home/runner/work/_actions/Homebrew/actions/master/wait-for-idle-runner/main.js:1:21)
2021-05-17T13:41:19.0388753Z     at Module._compile (internal/modules/cjs/loader.js:959:30)
2021-05-17T13:41:19.0389763Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
2021-05-17T13:41:19.0390735Z     at Module.load (internal/modules/cjs/loader.js:815:32)
2021-05-17T13:41:19.0392138Z     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
2021-05-17T13:41:19.0393375Z     at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) ***
2021-05-17T13:41:19.0394596Z   code: 'MODULE_NOT_FOUND',
2021-05-17T13:41:19.0395232Z   requireStack: [
2021-05-17T13:41:19.0396358Z     '/home/runner/work/_actions/Homebrew/actions/master/wait-for-idle-runner/main.js'
2021-05-17T13:41:19.0397150Z   ]

### CODE REVIEW

**Comment by iMichka** [comment]
@dawidd6 can you confirm that this is the way to do this? I am learning how to work with all of this along the way, so I'm stumbling over unexpected issues :)

**Comment by dawidd6** [comment]
Yes. This is the way. I see there are more inputs defined for this Action in `action.yml` file, but not retrieved in the script.

**Comment by iMichka** [comment]
> Yes. This is the way. I see there are more inputs defined for this Action in action.yml file, but not retrieved in the script.

Done

**Comment by dawidd6** [comment]
@iMichka I made some improvements to the code. Could you check if the logic is okay?

**Comment by dawidd6** [comment]
Ooops we force-pushed around the same time. Sorry for this.

**Comment by iMichka** [comment]
Thanks @dawidd6 for the improvements, I made some more changes.

**Pull request merged**
