### PR TITLE
check-commit-format: return failing status for non-compliant commits

### PR DESCRIPTION
**Pull request by carlocab**
Let's make this check return a failing status whenever the PR has
commits that don't follow our style guide. This will be a stronger
nudge to contributors to fix up their PR branch.

This currently isn't a required check in Homebrew/core, so it shouldn't
affect the rest of the CI run or our ability to merge PRs.

### CODE REVIEW

**Comment by dawidd6** [comment]
Are we going to drop/deprecate the autosquash functionality of `pr-pull`?

**Comment by carlocab** [comment]
I don't think so; `publish-commit-bottles` still needs it.

**Comment by MikeMcQuaid** [comment]
> Are we going to drop/deprecate the autosquash functionality of `pr-pull`?

IMO let's just lean into autosquash instead. I'm not sure I see why it's worth nudging users to change their commit messages if we can trivially fix it up ourselves.

**Comment by carlocab** [comment]
> IMO let's just lean into autosquash instead. I'm not sure I see why it's worth nudging users to change their commit messages if we can trivially fix it up ourselves.

A few reasons:
1. It's not really trivial, and still occasionally fails: https://github.com/Homebrew/homebrew-core/pull/128823#issuecomment-1515752655
2. It destroys status check information. To see this, compare the status checks you see for [this commit](https://github.com/Homebrew/homebrew-core/commit/91006b4dd9708323013b743ed3703f74ab5d547b) (not autosquashed), and [this commit](https://github.com/Homebrew/homebrew-core/commit/2e143a4a5b4d6a16163f0ec4d492a36f8fa903f1) (autosquashed). The autosquashed commit has no associated status check information.
3. The commit messages aren't great when it's not a version bump.

Destroying status check information wasn't such a big deal before since you could go back to the pull request and pull up the checks from there. But now that we push bottle commits to PR branches, those are no longer available either.

**Comment by MikeMcQuaid** [comment]
That's fair, thanks @carlocab. At a minimum it feels like autosquashing recording the existing commit hash in the commit message would be worthwhile.

**Comment by carlocab** [comment]
Superseded by #362.

For reference: I've fixed 1 and 2 in https://github.com/Homebrew/actions/pull/346#issuecomment-1515760663. 3 still happens, but those are relatively rare.

**Pull request closed without merging**
