### PR TITLE
download-artifact: use unzip command instead of library

### PR DESCRIPTION
**Pull request by dawidd6**
Fixes:

```
==> Commit: 81c199f1238894c379d5e5e27433a734740ab1a4
[@octokit/paginate-rest] "response.data.workflow_runs" is deprecated for "GET /repos/Homebrew/linuxbrew-core/actions/workflows/build-bottles.yml/runs". Get the results directly from "response.data"
==> Run: 64961837
==> Artifact: 3504117
events.js:187
      throw er; // Unhandled 'error' event
      ^
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:170:17)
Emitted 'error' event on DuplexWrapper instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at DuplexWrapper.onerror (_stream_readable.js:759:7)
    at DuplexWrapper.emit (events.js:210:5)
    at Parse.<anonymous> (/__w/_actions/Homebrew/actions/master/download-artifact/node_modules/duplexer2/index.js:45:12)
    at Parse.emit (events.js:210:5)
    at InflateRaw.<anonymous> (/__w/_actions/Homebrew/actions/master/download-artifact/node_modules/unzipper/lib/parse.js:188:46)
    at InflateRaw.emit (events.js:210:5)
    at Zlib.zlibOnError [as onerror] (zlib.js:173:8) {
  errno: -5,
  code: 'Z_BUF_ERROR'
}
```

https://github.com/Homebrew/linuxbrew-core/runs/541334549?check_suite_focus=true

Upstream commit: https://github.com/dawidd6/action-download-artifact/commit/d45f5489370f2ea474763a87feffbcaa22c1a6fa

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
What would you think about making this repo the main repo for action-download-artifact (and having admin permissions on it)?

**Comment by dawidd6** [comment]
I already have admin permissions here, @jonchang gave me :).
Also would like to keep my repo and just merge changes between if needed.

**Comment by jonchang** [comment]
Would this require changes in our workflows on Linux to install `unzip` again?

**Comment by dawidd6** [comment]
No, `unzip` is available on runners.

**Comment by jonchang** [comment]
Right, but they aren't available in our `homebrew/brew` image, which is why we needed to install `unzip` prior to migrating to Homebrew/actions/download-artifact.

```console
% docker run -it homebrew/brew              
root@25a9b6e17119:/home/linuxbrew# which unzip
root@25a9b6e17119:/home/linuxbrew# echo $?
1
```

Do `uses:` actions run _outside_ the container? Meaning, the system `unzip` command from the base image are accessible from the Javascript action?

**Comment by dawidd6** [comment]
Good catch, I wouldn't have thought that Node based Actions are actually run in container.
That's kinda strange for me.

https://github.com/dawidd6/action-download-artifact/runs/543164128?check_suite_focus=true

**Pull request closed without merging**
